apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-conf-datasources
  namespace: reservations-system
data:
  sources.yaml: |
    apiVersion: 1
    
    deleteDatasources:
      - name: Tempo
        orgId: 1
    
    datasources:
      - name: Tempo
        type: tempo
        url: http://tempo.reservations-system.svc:3200
        access: proxy
        isDefault: true
        jsonData:
          tracesToMetrics:
          datasourceUid: 'Prometheus'
          tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
          queries:
            - name: 'Sample query'
              query: 'sum(rate(traces_spanmetrics_latency_bucket{$__tags}[5m]))'
          serviceMap:
            datasourceUid: 'Prometheus'
          nodeGraph:
            enabled: true
          search:
            hide: false
          spanBar:
            type: 'Tag'
            tag: 'http.path'
        version: 1
        editable: true
      - name: Prometheus
        type: prometheus
        url: http://prometheus.reservations-system.svc:9090
        access: proxy
        jsonData:
          httpMethod: POST
          prometheusType: Prometheus
          prometheusVersion: 2.44.0
          nodeGraph:
            enabled: true
          search:
            hide: false
          spanBar:
            type: 'Tag'
            tag: 'http.path'
        version: 1
        editable: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.reservations-system.svc:3101
        jsonData:
          maxLines: 1000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-conf-dashboards
  namespace: reservations-system
data:
  dashboards.yaml: |
    apiVersion: 1
    
    providers:
      - name: dashboards
        type: file
        updateIntervalSeconds: 30
        options:
          path: /etc/dashboards
          foldersFromFilesStructure: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: reservations-system
data:
  reservations.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "description": "Reservations API",
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 1,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "PBFA97CFB590B2093"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 10,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 2,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "PBFA97CFB590B2093"
              },
              "editorMode": "builder",
              "expr": "requests{job=\"reservations\"}",
              "hide": false,
              "legendFormat": "__auto",
              "range": true,
              "refId": "A"
            },
            {
              "datasource": {
                "type": "prometheus",
                "uid": "PBFA97CFB590B2093"
              },
              "editorMode": "builder",
              "expr": "errors{job=\"reservations\"}",
              "hide": false,
              "legendFormat": "__auto",
              "range": true,
              "refId": "B"
            },
            {
              "datasource": {
                "type": "prometheus",
                "uid": "PBFA97CFB590B2093"
              },
              "editorMode": "builder",
              "expr": "goroutines{job=\"reservations\"}",
              "hide": false,
              "legendFormat": "__auto",
              "range": true,
              "refId": "C"
            },
            {
              "datasource": {
                "type": "prometheus",
                "uid": "PBFA97CFB590B2093"
              },
              "editorMode": "builder",
              "expr": "panics{job=\"reservations\"}",
              "hide": false,
              "legendFormat": "__auto",
              "range": true,
              "refId": "D"
            }
          ],
          "title": "Reservations API - Metrics",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "tempo",
            "uid": "P214B5B846CF3925F"
          },
          "fieldConfig": {
            "defaults": {
              "custom": {
                "align": "auto",
                "cellOptions": {
                  "type": "auto"
                },
                "inspect": false
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 10,
            "w": 12,
            "x": 12,
            "y": 0
          },
          "id": 1,
          "options": {
            "cellHeight": "sm",
            "footer": {
              "countRows": false,
              "fields": "",
              "reducer": [
                "sum"
              ],
              "show": false
            },
            "showHeader": true
          },
          "pluginVersion": "10.1.0",
          "targets": [
            {
              "datasource": {
                "type": "tempo",
                "uid": "P214B5B846CF3925F"
              },
              "key": "Q-9fc3b403-aa1a-4311-978b-cda05474ac3e-0",
              "limit": 20,
              "queryType": "nativeSearch",
              "refId": "A",
              "serviceName": "reservationist"
            }
          ],
          "title": "Reservations API - Traces",
          "type": "table"
        },
        {
          "datasource": {
            "type": "loki",
            "uid": "P8E80F9AEF21F6940"
          },
          "gridPos": {
            "h": 19,
            "w": 24,
            "x": 0,
            "y": 10
          },
          "id": 3,
          "options": {
            "dedupStrategy": "none",
            "enableLogDetails": true,
            "prettifyLogMessage": false,
            "showCommonLabels": true,
            "showLabels": false,
            "showTime": false,
            "sortOrder": "Descending",
            "wrapLogMessage": false
          },
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "uid": "P8E80F9AEF21F6940"
              },
              "editorMode": "builder",
              "expr": "{app=\"reservations\", container=\"reservations\"} | json",
              "key": "Q-844e3db6-67df-45db-8abb-dc8d357d6ce2-0",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Reservations API - Logs",
          "type": "logs"
        }
      ],
      "refresh": "5s",
      "schemaVersion": 38,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-15m",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Reservations API",
      "uid": "ccad8cb7-1592-4328-b38b-b4226a5d00a6",
      "version": 1,
      "weekStart": ""
    }
