apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: reservations-system
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - name: http-grafana
      port: 3100
      targetPort: http-grafana