kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  # Reservations-Api
  - containerPort: 3000
    hostPort: 3000
  # Reservations-Api debug
  - containerPort: 4000
    hostPort: 4000
  # Metrics Prometheus
  - containerPort: 4020
    hostPort: 4020
  # Grafana
  - containerPort: 3100
    hostPort: 3100
  # Database
  - containerPort: 5432
    hostPort: 5432
  # Redis
  - containerPort: 6379
    hostPort: 6379
  # Tempo (tracing)
  - containerPort: 9411
    hostPort: 9411